"""edit Book model

Revision ID: bd1eaab492dc
Revises: 29a5f2a8253a
Create Date: 2025-01-31 00:33:50.254216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1eaab492dc'
down_revision: Union[str, None] = '29a5f2a8253a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Books', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='unique')
    # ### end Alembic commands ###
